### ISSUE TITLE
Cannot search for books

### ISSUE THREAD

**Issue by jdsmo** [linuxserver/docker-readarr#19]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Try to search for an author, book, edition, etc. And it always returns: Failed to load search results, please try again.

## Current Behavior

Fails

## Steps to Reproduce

1. Install Docker container. using: `docker run -d   --name=readarr   -e PUID=1000   -e PGID=1000   -e TZ=America/Chicago   -p 8787:8787   -v /configs/readarr/config:/config   -v /media/Books:/books   -v /media/complete:/downloads   --restart unless-stopped   linuxserver/readarr:develop`
2. Search.
3. Try to debug with help on Reddit.
4. Check with trace log and see this: https://pastebin.com/MxDRZEab
5. Inside shell of container try to reach the problematic site with curl and get this: https://pastebin.com/EUi9VLhX
6. Readarr support says that it is a container problem. 

## Environment
**OS:** Ubuntu 18.04
**CPU architecture:** x86_64
**How docker service was installed:** From CLI, see above.

## Command used to create docker container (run/create/compose/screenshot)

See above.

## Docker logs

These are in the pastebin links above, but here is a sample:
```
Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. 

[v0.1.0.1248] NzbDrone.Core.MetadataSource.Goodreads.GoodreadsException: Search for 'work:4912783' failed. Invalid response received from Goodreads.
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.SearchForNewBook(String title, String author, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 224
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.SearchForNewEntity(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 134
   at lambda_method171(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Readarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Readarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Readarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Readarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Readarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

```

**Comment by DennisYildirim** [comment]
yeah no one cares i guess, so frustrating to see people developing apps without a single project management policy. Half the program does not do what it is supposed to do. They can't even fix the simplest issues... I will just uninstall i guess and let this stuff go. Calibre also does not work properly on synology. Looks like they are saying : calibre is not designed to work on network shares. But then they publish docker containers to work on network shares :D Complete eclipse of reason.
